// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC34gvfqO7EU5ay4RdWFNtJPTuGkYs3Tz8',
    appId: '1:243167542129:web:973a3ead1a5882453a54d0',
    messagingSenderId: '243167542129',
    projectId: 'api---trash',
    authDomain: 'api---trash.firebaseapp.com',
    storageBucket: 'api---trash.appspot.com',
    measurementId: 'G-N3LCXRLXZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYLDUysd_LHodlVrgHTJfF2VMKQL2zFXg',
    appId: '1:243167542129:android:cb62e879cfd468b73a54d0',
    messagingSenderId: '243167542129',
    projectId: 'api---trash',
    storageBucket: 'api---trash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzpO-K9Qh7hzXKZoLtlOm1t9OD5pE2b5s',
    appId: '1:243167542129:ios:72f314590a9e16e73a54d0',
    messagingSenderId: '243167542129',
    projectId: 'api---trash',
    storageBucket: 'api---trash.appspot.com',
    iosClientId: '243167542129-3kjevsbp8anl8odoa9m3ni2lp8i004lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationLixo',
  );
}
